import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import AuthProvider from "@/context/AuthContext";
import { ContextProvider } from "@/context/UserContext";
import { SocketProvider } from "@/context/SocketContext";
import { Toaster } from "@/components/ui/toaster";
import ContactsProvider from "@/context/ContactsContext";
import WebRTCProvider from "@/context/WebRTCContext";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ContextProvider>
        <ContactsProvider>
          <SocketProvider>
          <WebRTCProvider>
      <body
       className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}
      >
        {children}
        <Toaster/>
        </body>
         </WebRTCProvider>
        </SocketProvider>
         </ContactsProvider>
        </ContextProvider>
        </AuthProvider>
    </html>
  );
}
